### ISSUE TITLE
Respect minimal dimension during cropping

### ISSUE THREAD

**Issue by sboerrigter** [joppuyo/acf-image-aspect-ratio-crop#7]
The cropped image size should not be smaller then the Aspect Ratio Width and Height or Minimal Width and Height, to prevent blurry low quality images.

**Comment by joppuyo** [comment]
Hey, thanks for raising this issue. This plugin is meant to be used with aspect ratios, such as 16:9 rather than an exact pixel count. That's why it doesn't make sense to limit the cropped size, otherwise, 16:9 would equal to the minimum pixel count of 16 and 9 pixels.

But I think your use case makes sense so I'll look into adding the pixel-based minimum width/height as a separate option in the future.

If you want crop with minimum height behavior right away, I suggest [ACF Image Crop](https://fi.wordpress.org/plugins/acf-image-crop-add-on/) which is based on this principle.

**Comment by sboerrigter** [comment]
Thanks for your reply. I have looked into ACF Image Crop, but I think it has some other disadvantages. I like your plugin better except for the missing min- width and min- height restrictions. I think this is an important feature to prevent users to select low-quality images. Thanks for looking into it!

**Comment by R3dRidle** [comment]
The option for the pixel-based version is a must in my opinion.
This way you will never use an image that is larger than it should be in your design, thus you prevent using images that are TOO big.

The aspect ratio doesn't make sense I think. You can have the same effect with the pixels and it is more precise.

For example:
If I have an aspect ratio of 300x200 and crop an image, it COULD be that the image is larger than 300x200px. But probably the biggest image is this is size.

Please make this an option.

**Comment by jameelmoses** [comment]
Agree with this. This is the only reason I'm still using ACF Image Crop.

**Comment by joppuyo** [comment]
Hey!

My main use case for this plugin is responsive images. You talk about a 300x200 image, but have you considered that if an user visits your site on a Retina MacBook Pro or and iPad, you should provide a 600x400 image or otherwise they will encounter blurry images? Same with mobile phones. If your site is responsive and the image is displayed at full width of the screen, it might be 750, 1080 or 1440 pixels wide. A 300x200 image would look hopelessly blurry.

That’s why I use srcset and sizes attributes on the img tag to provide several different versions of the image for different screen resolutions.

I’m not saying that you guys are doing it wrong, I’m just saying that this is the rationale why I wrote this plugin as ACF Image Crop did not provide this and they did not accept my [pull request](https://github.com/andersthorborg/ACF-Image-Crop/pull/59). I don’t think the plugin is very actively maintained any more.

I’m not sure I want to replicate the functionality of the other plugin and I certainly did not want to do it when I first wrote this plugin since the other plugin was relatively maintained at that point in time.

**Comment by jameelmoses** [comment]
I understand the responsive images tie, but I think we're just suggesting the ability to still impose a min and max. Just like you wouldn't want to load a 300x200 image on a retina display instead of 600x400, I also don't want to deliver a 6000x4000 image.

**Comment by joppuyo** [comment]
If you want to get an exact pixel width image with this plugin, you can add something like this in your theme:

```php
add_action( 'init', function() {
    add_image_size('myproject-300', 300);
});
```

And then in your template:

```
$image = get_field('image', $post);

if (!empty($image['sizes']['myproject-300']) && $image['sizes']['myproject-300-width'] === 300) {
    // found correct size image
    $url = $image['sizes']['myproject-300'];
} else {
    // image < 300px, use original url
    $url = $image['url'];
}

echo "<img src='$url' alt=''>";
```

This of course assumes you set the aspect ratio correctly when defining the field.

I'm planning on adding a feature at some point which allows you to select which thumbnail sizes are generated for the cropped image as per this [issue](https://github.com/joppuyo/acf-image-aspect-ratio-crop/issues/10).

**Comment by joppuyo** [comment]
I'm not still sure what would be the best way forward for building a pixel crop functionality.

* Add pixel cropping to this plugin in addition to aspect ratio cropping?
* Create a new plugin, let's say something like _ACF Image Crop EX_ that only does aspect ratio crop?
* Add pixel cropping to this plugin and rename it to something like _ACF Image Crop EX_ ?
* Hope the other plugin gets updated
* Something else?

**Comment by jameelmoses** [comment]
a good idea might be to have a toggle in the options for the field on creation to either do by aspect ratio or a hard crop with defined dimensions. that provides ultimate flexibility. viewing the code from ACF Image Crop would probably make it pretty low-hanging fruit to achieve that way. just a thought. im happy to contribute too if you'd like.

**Comment by jameelmoses** [comment]
the downside to your method above is that you'd have to create an image size for every image field in your site with unique size parameters. then whenever an image is uploaded, you've got tons of sizes for images never applicable to that field. i know file storage is cheap, but it just seems unnecessary.

**Comment by joppuyo** [comment]
> the downside to your method above is that you'd have to create an image size for every image field in your site with unique size parameters. then whenever an image is uploaded, you've got tons of sizes for images never applicable to that field. i know file storage is cheap, but it just seems unnecessary.

Yep, that is definitely a downside of using this method.

> a good idea might be to have a toggle in the options for the field on creation to either do by aspect ratio or a hard crop with defined dimensions. that provides ultimate flexibility. viewing the code from ACF Image Crop would probably make it pretty low-hanging fruit to achieve that way. just a thought. im happy to contribute too if you'd like.

I think this is a good idea. If you have time to contribute just send a pull request and I'll review and merge it.

I think it would be good to default to aspect ratio crop since was the original intention of the plugin.

**Comment by R3dRidle** [comment]
Hey,

Just for info, how are you doing on this point?

**Comment by joppuyo** [comment]
Hey @sboerrigter , @R3dRidle and @jameelmoses , an option to use a pixel size instead aspect ratio has been added in plugin version v3.2.0.

Here's how it works from the readme

> ## Pixel size
>
> Use this option if you need a specific pixel size image like 640×480. User will not be able to select an image smaller than the defined pixel size.
>
> After selecting an image, user can select an area from the image they want, which can be larger than the pixel size but may not be smaller. The aspect ratio of the selection is locked according to the pixel size.
>
> When crop button is pressed, the area is cropped from the original image. After the crop is complete, the image will be automatically scaled down to the pixel size. This means the final image will always be the specified size.

Could you check that this feature now works like you expect?

Thanks!

**Comment by R3dRidl3** [comment]
Do you allso create other image sizes in the same ratio for the srcset?

**Comment by R3dRidl3** [comment]
I will test this in a few days

**Comment by joppuyo** [comment]
> I will test this in a few days

Thanks!

> Do you allso create other image sizes in the same ratio for the srcset?

Yes, if the thumbnail sizes are smaller then the image size specified in the field.

**Comment by jameelmoses** [comment]
@joppuyo perfect! thanks for the add! it works beautifully

**Comment by joppuyo** [comment]
Glad you like it!

I will add a change in a future version so that min width and height are taken into account also when using the aspect ratio option.

**Comment by R3dRidl3** [comment]
Now it looks like it's 100% interchangable with the old plugin, thank  you for that!

I would have 1 more request though if possible, in the old one you could seelect the image sizes with a drop down wich you had defined in your theme.

Hope to see this feature :)

**Comment by R3dRidl3** [comment]
@joppuyo 
It is not possible to add height 0 (dynamic height).

The other plugin had the option:
Leave blank for no restriction (does not work with hard crop option)

So let's say I want an image to have a width of 300 but don't want the height to be restricted. Sometimes I want a height of 600 and sometimes of 200 depending on the image and the text next to the image.

Could you add this option?

Allso previously asked:
I would have 1 more request though if possible, in the old one you could seelect the image sizes with a drop down wich you had defined in your theme (with add_image_size).

**Comment by joppuyo** [comment]
> So let's say I want an image to have a width of 300 but don't want the height to be restricted. Sometimes I want a height of 600 and sometimes of 200 depending on the image and the text next to the image.
> Could you add this option?

I know there were a lot of options in the older plugin but many of them did not make much sense to me so I did not implement them. This plugin is primarily meant to deal with aspect ratios and having one dimension locked and one dimension free is basically the same thing as a free crop. And a free crop is something that will be implemented once I have merged this [pull request](https://github.com/joppuyo/acf-image-aspect-ratio-crop/pull/24).

> I would have 1 more request though if possible, in the old one you could seelect the image sizes with a drop down wich you had defined in your theme (with add_image_size).

I know this was a feature the older plugin but I don't intend this plugin to have 100% feature parity with that plugin. I know having this feature would mean a bit less typing but it's also more work for me to implement and to support in the future.

**Comment by R3dRidl3** [comment]
@joppuyo how are you doint on this one? 
Since https://github.com/joppuyo/acf-image-aspect-ratio-crop/pull/24 is merged a while back.

**Comment by joppuyo** [comment]
That PR has been merged to to the project sincr 3.3.0. Please download the latest version and see if it works for you.

**Comment by R3dRidl3** [comment]
@joppuyo I am still missing the ability to have a width say 600 and a dynamic (free) height in the pixels option.

**Comment by joppuyo** [comment]
Sorry, but as I said, I don't have a plan adding this feature to the plugin since it's out of scope.

This plugin deals primarily with aspect ratios and having one axis locked to a pixel size and one free is essentially the same as a free aspect ratio.

**Comment by R3dRidl3** [comment]
I will check out if it works for me in my next project
